### ISSUE TITLE
Sub-Directories make it hard to link to RFCs: how about using a status-field instead?

### ISSUE THREAD

**Issue by ligthyear** [maidsafe/rfcs#120]
I understand and totally agree that the way rust handles their RFCs is pretty unclear regrading the state of each RFC and see the reason behind creating the folders. However, this makes it hard to link to any RFC as their link throughout the development cycle changes significantly, one reason why RFCs can't properly link to each other directly within the document.

Coming from the [Python PEP Process](https://www.python.org/dev/peps/) (which the rust RFC process is largely inspired by), how about adding a top-level field `status` instead like they do (and maybe one that mentions the release version once it was published)? This way, each RFC could stay in one place and be linked to.

In regards to have a good overview, I'd suggest to do it similarly as Rust does it and just link the RFCs from the Readme.md, but as sections depending their status (ordered by number, optionally descending). Changing the status then needs to be PR which also moves them from one section to another.

**Comment by dirvine** [comment]
Nice idea. @rossmuir can certainly help here. He is currently pushing the RFC process and making it more friendly. I like the status field idea as it will keep links clear and valid. @rossmuir can you please jump in and help out here. Some really good ideas and several fixes. This will help a lot with the current push for clarity and more community involvement.

**Comment by rossmuir** [comment]
Sure @dirvine sounds good - I will check out the Python PEP Process - thanks @ligthyear

**Comment by ligthyear** [comment]
I'm happy to make a PR with the changes (moving all RFCs into one sub-dir and adding a `status`-flag in the top, and optionally link all RFCS to one another and their appropriate github tickets), if that'd be helpful and accepted.

**Comment by rossmuir** [comment]
@ligthyear that would be very helpful thanks :+1:  - sorry I have not got to this. This will improve linking and simplify the process - thank you.

**Comment by rossmuir** [comment]
Thank you @ligthyear - This really does simplify and improve the process.
