### ISSUE TITLE
#0049 PARSEC

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/rfcs#224]
**PARSEC - Protocol for Asynchronous, Reliable, Secure and Efficient Consensus**
---
Summary:

> In this RFC, we propose an algorithm which will allow a section of network nodes to reach consensus on the validity and order of network events by voting on events and using a gossip protocol to disseminate these votes amongst themselves. The main claim of this RFC is:
> 
> All honest participating nodes will reach eventual Byzantine agreement with probability one on a total order of valid blocks, where the valid blocks are comprised of a supermajority of valid votes by the nodes on NodeStates.

- Project: https://github.com/maidsafe/rfcs/tree/master/text/0049-parsec
- ReadMe: https://github.com/david-maidsafe/rfcs/blob/master/text/0049-parsec/0049-parsec.md
- Forum Discussion: https://forum.safedev.org/t/rfc-49-parsec/1707

---

**Comment by Lindsey17** [comment]
Implemented
