### ISSUE TITLE
#0050 Transparent Malice Handling within PARSEC

### ISSUE THREAD

**Issue by david-maidsafe** [maidsafe/rfcs#277]
# Transparent Malice Handling within PARSEC

ℹ️  Summary:
> In this RFC, we propose methods of identifying and dealing with nodes acting with differing types of malicious intent within a section. When the section identifies and reaches consensus that a particular node is a malicious agent then that node is then ejected from the section.

- 📚  [ReadMe (the RFC proposal)](https://github.com/maidsafe/rfcs/blob/master/text/0050-malice_in_parsec/0050-malice_in_parsec.md)
- ✍️  [Discussion (SAFE Network Forum)](https://safenetforum.org/t/rfc-50-transparent-malice-handling-within-parsec/25487)

**Comment by Lindsey17** [comment]
Implemented
