### ISSUE TITLE
#0053 XOR-URLs (XOR-name based URLs)

### ISSUE THREAD

**Issue by joshuef** [maidsafe/rfcs#285]
Discussion: https://forum.safedev.org/t/rfc-discussion-xor-urls/2365

RFC: https://github.com/maidsafe/rfcs/blob/master/text/0053-xor-urls/0053-xor-urls.md

TODO : 

- [ ] Update proposal to consider limitations of using `port` number in the URL scheme.
- [ ] Fully consider alternative proposals for encoding / structure from: https://forum.safedev.org/t/rfc-discussion-xor-urls/2365/13

**Comment by b-zee** [comment]
Is there an issue, @joshuef ? ;)

**Comment by joshuef** [comment]
Sorry I totally missed your response @b-zee!

It's preferred for discussion to take place on the forum, which you can find over here: https://forum.safedev.org/t/rfc-discussion-xor-urls/2365
