### ISSUE TITLE
Spam Prevention ?

### ISSUE THREAD

**Issue by vigneshwara044** [maidsafe/rfcs#306]
As mentioned in the fundamental  [#3](https://safenetwork.tech/fundamentals/#9ffbcb344fk), there will be no cost in transferring SAFE coins, then there could be a spam (DOS) attack by a malicious actor who could simply transfer SAFE coins between his/her wallets and this could induce a strain on the elders. This wouldn't cost the malicious actor much as there are no transaction fees and the malicious actor could just divide a SAFE coin into 250 * 10^-12 and transfer all of them simultaneously and repeatedly between different wallets.

**Comment by dirvine** [comment]
Sending amounts will go through PARSEC on clients Elder section, they will be slowed somewhat. If duplicate calls then they won't make it through PARSEC. 
SPAM in general though is a huge subject, just Get spam is possible at the moment (there is a really nice approach to that though) and much more. I intend we have an anti-spam RFC to cover all possible SPAM with a system that is network wide.

**Comment by vigneshwara044** [comment]
Closed.
