### ISSUE TITLE
Add `GetKey` Request and Response variants for AppendOnlyData

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/rfcs#315]
We should support an RPC for requesting a certain key from all kinds of AppendOnlyData objects (Unseq + Unpub, Unseq + Pub, Seq + Unpub, Seq + Pub). Because the keys are supposed to be unique, it should be straightforward enough to build an index for them on the Vaults side, so this operation will be efficient.

Proposed implementation:
```rust
pub enum Request {
    ...
    // Get a specified key from AppendOnlyData.
    // Only the owner(s) can perform this operation on unpublished data.
    GetADataKey {
        kind: AppendOnlyKind,
        address: AppendOnlyDataRef,
        // Key to look up.
        key: Vec<u8>,
        // Requester public key.
        requester: BLS-PublicKey,
    },
    ...
}

pub enum Response {
    /// Returns a corresponding value and index if the key is found.
    /// If the key is not found, an error will be returned.
    GetADataKey(Result<(Vec<u8>, u64)>, ClientError>),
}
```

**Comment by lionel1704** [comment]
Sounds good to me.
One small thing, should we name this request, `GetADataValue` or `GetADataEntry`?

**Comment by nbaksalyar** [comment]
Yes, `GetADataValue` sounds better. :slightly_smiling_face: 

`GetADataEntry` would imply that you get both key + value.
`GetADataKey` implies you get a key given a value.
And `GetADataValue` sounds just right :+1:
