### ISSUE TITLE
Discuss Agreed - 0009-MPID-Messaging

### ISSUE THREAD

**Issue by Viv-Rajkumar** [maidsafe/rfcs#50]
https://github.com/maidsafe/rfcs/tree/master/agreed/0009-MPID-Messaging

**Comment by brian-js** [comment]
https://github.com/maidsafe/rfcs/pull/85 has conflicting definitions for `MpidManager`. The second having `OutboxAccount` and `InboxAccount` while only `Account` is defined.

**Comment by maqi** [comment]
Thx.
It is now resolved. the second one shall be removed.

**Comment by rossmuir** [comment]
Moved to Active > https://github.com/maidsafe/rfcs/issues/96
