### ISSUE TITLE
RFC 0000 discussion

### ISSUE THREAD

**Issue by dirvine** [maidsafe/rfcs#6]
Please help to discuss and improve / debate this rfc 
https://github.com/maidsafe/rfcs/blob/master/proposed/0000-Remove-Transaction-Managers.md

**Comment by benjaminbollen** [comment]
Question 1: For FixedStructuredData a given set of owners can only own a instance of a given type?  Can you present a use-case for FixedStructeredData?

**Comment by benjaminbollen** [comment]
Question 2: this multi-signature is a separate issue from MSID; ie such a StructuredDataType could be signed by an MSID key and then all 'participants' of that MSID would be able to individually modify the type?

**Comment by benjaminbollen** [comment]
Question 3: should some tag_types be protected; in particular for safecoin?

**Comment by dirvine** [comment]
@benjaminbollen 
Q1: This will be handy for things like private shares, where owners can be removed and the data itself will move to a new location. Particularly if such data is public (so not encrypted but signed). If somebody wants to create a global app or even programming language they would be able to use this type and own it, deciding to encrypt or not the contents. 
Q2: I think with this structure the MSID may no longer be required, in this new way 'new' members of a share for instance may be barred from changing older data, unless the end user app wants them to and then it needs approval of the majority again. As users // owners are swapped around like this the data locations change (if you want that or use Transferable types to maintain the history). It becomes a matter for app devs. The transferable types can be used to create coins / contracts etc. 
Q3: I think for safecoin it probably has more rules than most, so we have a different mechanism for creating these (network must create them in a chain for protection). So safecoin for us may not be covered with these types AFAIK. Nice if they did, but for now it's safer to keep them separate.

**Comment by benjaminbollen** [comment]
Question 4 - more a proposal / open question: can we provide an additional type for structured data: ReversedLinkData.  A fixed structure data type where public write access is allowed to link back to an original data type;  similar to the problem Google solves for forward linked hyperlinks

**Comment by dirvine** [comment]
Q3: Continued. I think we cannot control the types so there will probably be no attempt to protect them.
Q4: I thin the beauty of this is that the data elements are completely in the control of the app devs, so type 999 for instance could be semantic data. The data element is not regulated by us at all so could be any structure people wish (including web indexes for instance). 

A slight addition would be recognise data types to include owners, then it makes spamming difficult and also provides a unique space for everyone. So you would know 999 + your public_id is yours and cannot be touched. Maybe FixedStructuredData should in fact adhere to that?

**Comment by benjaminbollen** [comment]
Q1: but will the tag_type not be "over-scattered": should every new application have a unique tag_type; or will the tag_types only be defined for the owner - in the other extreme?

**Comment by dirvine** [comment]
Initially it will be up to the app devs. So an app may choose 999 and so may several, with such a vast address space it may be difficult to collide, but possible. I don't see that being an issue actually, but worth watching for in the design. Adding owners as part of name does make this extremely hard to attack a space / type combination. In TransferrableStructuredData the identifier is a random number so could be targeted. Worth consideration (I don't like the Identifier)

**Comment by benjaminbollen** [comment]
Q2: if there would be no MSID then can we still do a collaborative editing; or would such an application require a tree structure for resolving merge-conflicts, and as such be built on a higher level; if that is the case, does an app have the tools for this (brainstorm question)?

**Comment by dirvine** [comment]
Q2: Yes it is up to apps to create such tools for sure. Instead of MSID the private key (read only access for public shares)  is just sent via messaging to users. Owners are now able to prevent a single owner deleting everything if they wish (on a per directory level). So can provide greater granularity. 
These data types do not evne try to handle merge conflicts as this can be pushed back to app devs to ensure they provide SDV like structures that can be handled locally. Of course network level locks etc. are still on the cards, just not in this rfc.

**Comment by benjaminbollen** [comment]
Q4: if we allow MPID-messaging sent a public data type, to be publicly readable then we might have a 2-for-1 solution to "post-reply-on-forum" type actions

**Comment by dirvine** [comment]
Yes indeed :+1:

**Comment by benjaminbollen** [comment]
Q2: I can see that there is no value for MSID anymore if these keys are indeed exchanged over MPID and saved in the MAID (or not saved)

**Comment by dirvine** [comment]
They are stored by the client and just key pairs now. So many types can be created there. They would be sent via MPID and the client apps will use this to accept/reject access to a share etc.

**Comment by benjaminbollen** [comment]
oneline resolution for Q2, Q3, and Q4 updated above in the question.
Q1: so FixedStructuredData are not intended for your "private word document"? More for your "Collaboration X produced Y" type of data? (would we not run into many collisions (between apps) for only 4bytes of "identifier" - Im sorry Im still confused on imagining a FixedStructuredData

**Comment by benjaminbollen** [comment]
Q5: will we not lose the version-history if the version number is not included in the name calculation?

**Comment by benjaminbollen** [comment]
Unresolved question 2: "Version conflics or out of order updates, will upper layers handle this via a wait condition?" this can be addressed by Routing having the `ActionSentinel` in combination with the version number

**Comment by dirvine** [comment]
Q5 if client apps include version history then it's OK this data is structured data so can be anything at all in the data component. So for us we can store DIR's there fro private data or even public data. If the dir component includes version history then folk will use it. If somebody else did another DIR type then it would not be used so much perhaps.

**Comment by dirvine** [comment]
I thin the main point is that this is StructuredData handled by the network, what the data component holds is entirely up to all developers. Si imagine what we have now with Directory handling, but then allow users to use any structure at all (up to 100kB) and link structures or content (by including a datamap)

**Comment by dirvine** [comment]
I think you have a point @benjaminbollen A single type of structured data (here Transferable) covers all use cases we can think of. Especially as this can now include a delete call from owners. So any history can be removed. That simplifies thinking as well which is nice. I will update PR with just a single type.

**Comment by maqi** [comment]
I think the original main point of this RFC is come from the intention to remove the present Version Handler.
And this is only achievable based on the following assumptions : 
1, The SDV shows its owner/owners, and such ownership is verifiable
2, PmidNode will carry out "replacement" based on the rule that only the owner is allowed to update the SDV or transfer the ownership
3, It is totally upto the client to compose such SDV, as long as it can provide a proper signature to prove the ownership
4, any updating to SDV's member data must follow a generic rule, for example : tag_type and identifier must be kept the same, version can only be increment,
5, user can create their own app using any non-conflict tag num, however the above generic rule must be followed, and it is up to their app to parse / re-put / compose SDV to the network

unfortunately, the previous defined Transaction Manager carries out some other additional work : 
1, It needs to verify the proof when one coin is first generated on the network
2, it needs to carry out m+n majority voting verification, which is not generic as for coin usage, it is transfer the ownership but for other use case it may means update SDV content

I think trying to remove Transaction Manager might be a too long shot, probably the RFC to be renamed as removing Version Handler ?

**Comment by dirvine** [comment]
@maqi I agree with your first 5 points and this is key. If we push the responsibility of data content and correctness back to the client (who follows simple rules) then this allows clients to create any data types themselves. So I feel this is a really nice feature and will free app devs. 

On the sub points I think there is a trick that may be being missed. So for 
1. In this case say a complex data item like safecoin requires several things to happen on the network. This is now possible by having safecoin farming take several steps, at each step it produces a new type i.e. (this is altered for example of any type) 
safecoin_a -> Farming attempt (data element includes proof of attempt)
safecoun_b -> Verification token (verifies all nodes fit criteria)
safecoin_c -> Mint version -> stores coin for claim 
safecoin -> Coin is claimed (signed by owner)

Just as an example really, in our case the vaults themselves see this data and act on it appropriately. I am not suggesting we do this with safecoin right now though. I am doing some code to test out the hypothesis at the moment (it requires a slightly different type that is unsigned). This is how such a complex chain would work for network generated info like safecoin (app devs would not do this as they would have some alternative farming/mining methods)

2. For M:N sharing then this is also handled client side. So an owner creates a 'not fully signed' StructuredData and sends to the next owner who will sign (can be done many ways, even with a private share so folk sign till quorum is met, or an app that does this). When a quorum is met then send the StruicturedData to the network via a `Post` to update previous version. If a chunk fails quorum verification then the network just rejects it. Again this simplifies vaults and provides flexibility for users.

**Comment by benjaminbollen** [comment]
Q5: +1 the version number purely for SAFE to sync the updates makes a lot of sense; if a client app chooses to keep the history it can do that in the data field; SAFE should not force to keep all history

**Comment by dirvine** [comment]
Please make any relevant updates to new rfc published here for review. https://github.com/maidsafe/rfcs/pull/11/files
